# permissions for end users to edit terminals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: marina-operator
    app.kubernetes.io/managed-by: kustomize
  name: terminal-editor-role
rules:
- apiGroups:
  - core.marina.io
  resources:
  - terminals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.marina.io
  resources:
  - terminals/status
  verbs:
  - get
