# permissions for end users to view terminals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: marina-operator
    app.kubernetes.io/managed-by: kustomize
  name: terminal-viewer-role
rules:
- apiGroups:
  - core.marina.io
  resources:
  - terminals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.marina.io
  resources:
  - terminals/status
  verbs:
  - get
