apiVersion: terminal.marina.io/v1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/instance: user-sample
    app.kubernetes.io/part-of: marina-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: marina-operator
  name: user-sample
spec:
  # TODO(user): Add fields here
